<?php

namespace Database\Seeders;

use App\Models\Lansia;
use Illuminate\Database\Seeder;

class DummyLansiaSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            [
                'nama_lengkap' => 'Aisyah Nur',
                'nik' => '3175010101010001',
                'tempat_lahir' => 'Pekanbaru',
                'jenis_kelamin' => 'P',
                'tanggal_lahir' => '1954-03-12',
                'agama' => 'Islam',
                'nomor_kk' => '1471010101010001',
                'pendidikan_terakhir' => 'SMP',
                'tanggal_masuk' => '2025-02-15',
                'alamat_asal' => 'Jl. Harapan Raya',
                'daerah_asal' => 'Pekanbaru',
                'no_kamar' => 'A-101',
                'status' => 'aktif',
                'riwayat_penyakit' => 'Hipertensi',
                'alergi' => '-',
            ],
            [
                'nama_lengkap' => 'Rukmini Sari',
                'nik' => '3175010101010002',
                'tempat_lahir' => 'Siak',
                'jenis_kelamin' => 'P',
                'tanggal_lahir' => '1958-08-22',
                'agama' => 'Islam',
                'nomor_kk' => '1471010101010002',
                'pendidikan_terakhir' => 'SD',
                'tanggal_masuk' => '2025-04-05',
                'alamat_asal' => 'Jl. Riau',
                'daerah_asal' => 'Siak',
                'no_kamar' => 'B-203',
                'status' => 'aktif',
                'riwayat_penyakit' => 'Diabetes ringan',
                'alergi' => 'Udang',
            ],
            [
                'nama_lengkap' => 'Sulastri',
                'nik' => '3175010101010003',
                'tempat_lahir' => 'Dumai',
                'jenis_kelamin' => 'P',
                'tanggal_lahir' => '1960-01-30',
                'agama' => 'Islam',
                'nomor_kk' => '1471010101010003',
                'pendidikan_terakhir' => 'SMA/SMK',
                'tanggal_masuk' => '2025-07-19',
                'alamat_asal' => 'Jl. Sudirman',
                'daerah_asal' => 'Dumai',
                'no_kamar' => 'A-102',
                'status' => 'aktif',
                'riwayat_penyakit' => '-',
                'alergi' => '-',
            ],
            [
                'nama_lengkap' => 'Nurhayati',
                'nik' => '3175010101010004',
                'tempat_lahir' => 'Rokan Hulu',
                'jenis_kelamin' => 'P',
                'tanggal_lahir' => '1957-11-09',
                'agama' => 'Islam',
                'nomor_kk' => '1471010101010004',
                'pendidikan_terakhir' => 'SMP',
                'tanggal_masuk' => '2025-10-02',
                'alamat_asal' => 'Jl. Garuda Sakti',
                'daerah_asal' => 'Rokan Hulu',
                'no_kamar' => 'B-201',
                'status' => 'aktif',
                'riwayat_penyakit' => 'Asma',
                'alergi' => 'Debu',
            ],
            [
                'nama_lengkap' => 'Budi Santoso',
                'nik' => '3175010101010005',
                'tempat_lahir' => 'Pekanbaru',
                'jenis_kelamin' => 'L',
                'tanggal_lahir' => '1952-05-21',
                'agama' => 'Islam',
                'nomor_kk' => '1471010101010005',
                'pendidikan_terakhir' => 'SMA/SMK',
                'tanggal_masuk' => '2025-12-11',
                'alamat_asal' => 'Jl. Melati',
                'daerah_asal' => 'Pekanbaru',
                'no_kamar' => 'C-101',
                'status' => 'aktif',
                'riwayat_penyakit' => 'Kolesterol',
                'alergi' => '-',
            ],
            [
                'nama_lengkap' => 'Agus Salim',
                'nik' => '3175010101010006',
                'tempat_lahir' => 'Kampar',
                'jenis_kelamin' => 'L',
                'tanggal_lahir' => '1950-02-10',
                'agama' => 'Islam',
                'nomor_kk' => '1471010101010006',
                'pendidikan_terakhir' => 'SD',
                'tanggal_masuk' => '2026-01-14',
                'alamat_asal' => 'Jl. Suka Jadi',
                'daerah_asal' => 'Kampar',
                'no_kamar' => 'C-102',
                'status' => 'aktif',
                'riwayat_penyakit' => 'Hipertensi',
                'alergi' => '-',
            ],
            [
                'nama_lengkap' => 'Siti Rahmah',
                'nik' => '3175010101010007',
                'tempat_lahir' => 'Pelalawan',
                'jenis_kelamin' => 'P',
                'tanggal_lahir' => '1959-09-17',
                'agama' => 'Islam',
                'nomor_kk' => '1471010101010007',
                'pendidikan_terakhir' => 'SMP',
                'tanggal_masuk' => '2026-02-06',
                'alamat_asal' => 'Jl. Tanjung',
                'daerah_asal' => 'Pelalawan',
                'no_kamar' => 'B-205',
                'status' => 'aktif',
                'riwayat_penyakit' => '-',
                'alergi' => 'Telur',
            ],
            [
                'nama_lengkap' => 'Rudi Hartono',
                'nik' => '3175010101010008',
                'tempat_lahir' => 'Bengkalis',
                'jenis_kelamin' => 'L',
                'tanggal_lahir' => '1955-06-04',
                'agama' => 'Islam',
                'nomor_kk' => '1471010101010008',
                'pendidikan_terakhir' => 'SMP',
                'tanggal_masuk' => '2026-03-08',
                'alamat_asal' => 'Jl. Anggrek',
                'daerah_asal' => 'Bengkalis',
                'no_kamar' => 'C-201',
                'status' => 'aktif',
                'riwayat_penyakit' => 'Asam urat',
                'alergi' => '-',
            ],
            [
                'nama_lengkap' => 'Dewi Lestari',
                'nik' => '3175010101010009',
                'tempat_lahir' => 'Indragiri',
                'jenis_kelamin' => 'P',
                'tanggal_lahir' => '1956-12-01',
                'agama' => 'Islam',
                'nomor_kk' => '1471010101010009',
                'pendidikan_terakhir' => 'SMA/SMK',
                'tanggal_masuk' => '2026-05-20',
                'alamat_asal' => 'Jl. Mawar',
                'daerah_asal' => 'Indragiri',
                'no_kamar' => 'A-103',
                'status' => 'aktif',
                'riwayat_penyakit' => 'Maag',
                'alergi' => '-',
            ],
            [
                'nama_lengkap' => 'Andi Saputra',
                'nik' => '3175010101010010',
                'tempat_lahir' => 'Pekanbaru',
                'jenis_kelamin' => 'L',
                'tanggal_lahir' => '1953-07-27',
                'agama' => 'Islam',
                'nomor_kk' => '1471010101010010',
                'pendidikan_terakhir' => 'SMA/SMK',
                'tanggal_masuk' => '2026-06-11',
                'alamat_asal' => 'Jl. Kenanga',
                'daerah_asal' => 'Pekanbaru',
                'no_kamar' => 'C-202',
                'status' => 'aktif',
                'riwayat_penyakit' => 'Jantung',
                'alergi' => 'Kacang',
            ],
        ];

        foreach ($data as $row) {
            Lansia::create($row);
        }
    }
}
